# ARM workflow to run jacotest against https://github.com/texadactyl/jacobin.

name: ARM Jacotest with texadactyl Jacobin

on:
  workflow_dispatch:

jobs:

  run_jacobin:
    env:
      GOBIN: $HOME/go/bin
    strategy:
      fail-fast: false
      matrix:        
        os: [ubuntu-24.04-arm, windows-11-arm]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@main

    - name: Add Go to PATH
      run: echo "$HOME/go/bin" >> $GITHUB_PATH
      
    - name: Setup Go
      uses: actions/setup-go@main
      with:
          go-version: '1.24.x'
          cache: true
          cache-dependency-path: "**/go.sum"
          
    - name: Setup JDK on POSIX ARM64
      if: matrix.os != 'windows-11-arm'
      uses: actions/setup-java@main
      with:
        distribution: 'oracle'
        java-version: '21'

    - name: Set up JDK on Windows ARM64
      if: matrix.os == 'windows-11-arm'
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'           # or 'adopt', 'microsoft', depending
        java-version: '21'                # or whichever you choose
        architecture: 'arm64'             # key: choose arm64

    - name: Setup Jacotest
      shell: bash
      run: |
        cd src
        go get
        go install -v .
        cd ..
        jacotest -h

    - name: Setup Jacobin
      shell: bash
      run: |
        set -x
        git clone https://github.com/texadactyl/jacobin
        cd jacobin
        go install -v ./...
        echo PATH :: $PATH
        jacobin --version
      
    - name: Run Test Cases
      shell: bash
      run: |
        java --version
        javac --version
        jacotest -c -x || true

    - name: Summary of Results
      shell: bash
      run: |
        jacotest -r 3
